[package]
name = "flagfile-cli"
version = "0.1.3"
edition = "2021"
authors = ["Nikolajus Krauklis <nikolajus@gmail.com>"]

[[bin]]
name = "flagfile"
path = "src/main.rs"

[[bin]]
name = "ff"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.0", features = ["derive", "env"] }
flagfile-lib = { path = ".." }
ignore = "0.4"
regex = "1"
serde_json = "1.0.114"
